exit with error if frontend not detected (#2397)
If the frontend detection fails, it returns `none`, then the `./earthly`
script will attempt to run commands such as `none pull
docker.io/earthly/earthlybinaries:prerelease`, which results in a `none
command not found` which is difficult to debug.

diff --git a/earthly b/earthly
--- a/earthly
+++ b/earthly
@@ -38,10 +38,14 @@ detect_frontend() {
     return
   fi
 
-  echo "none"
+  echo >&2 "failed to detect docker/podman frontend"
+  exit 1
 }
 
-frontend_bin=$(detect_frontend)
+# some tests run ./earthly when no front-end is present; when EARTHLY_DISABLE_FRONTEND_DETECTION=true, skip detection.
+if [ "$EARTHLY_DISABLE_FRONTEND_DETECTION" != "true" ]; then
+    frontend_bin=$(detect_frontend)
+fi
 
 get_latest_binary() {
     "$frontend_bin" rm --force earthly_binary 2>/dev/null >&2 || true
