Warn if anonymous token is fetched (#4042)
Using a registry without logging in may lead to rate limiting; display a
warning if that's the case.

Note that this will be done in all instances even when using a local
buildkit instance.

fixes #3009

---------

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

diff --git a/tests/Earthfile b/tests/Earthfile
--- a/tests/Earthfile
+++ b/tests/Earthfile
@@ -212,6 +212,9 @@ ga-no-qemu-group10:
 ga-no-qemu-group11:
     BUILD --pass-args ./autoskip+test-group3
 
+ga-no-qemu-group12:
+    BUILD --pass-args ./warn-if-not-logged-in+test
+
 
 ga-no-qemu-slow:
     BUILD +server
@@ -235,6 +238,10 @@ ga-no-qemu:
     BUILD +ga-no-qemu-group6
     BUILD +ga-no-qemu-group7
     BUILD +ga-no-qemu-group8
+    BUILD +ga-no-qemu-group9
+    BUILD +ga-no-qemu-group10
+    BUILD +ga-no-qemu-group11
+    BUILD +ga-no-qemu-group12
     BUILD +ga-no-qemu-slow
 
 # Note that this target is split up under github action workflows
@@ -1848,16 +1855,22 @@ RUN_EARTHLY:
             exit \$exit_code
         fi
 
-        if $should_fail; then
+        if [ \"$should_fail\" = maybe ]; then
+            # This is for times when we do not care about the exit code
+            echo \"INFO: earthly exited with exit_code=\$exit_code; maybe this is ok?\"
+        elif [ \"$should_fail\" = true ]; then
             if [ \$exit_code -eq 0 ]; then
                 echo ERROR: earthly should have failed but didn\'t.
                 exit 1
             fi
-        else
+        elif [ \"$should_fail\" = false ]; then
             if [ \$exit_code -ne 0 ]; then
                 echo ERROR: earthly failed with exit code \$exit_code.
                 exit \$exit_code
             fi
+        else
+            echo ERROR: unexpected value for should_fail: $should_fail
+            exit 1
         fi
         if [ -n \"$output_contains\" ]; then
             if ! grep $grep_flags \"$output_contains\" earthly.output >/dev/null; then
