support for ecr-login (#2668)
This implements support for using ecr-login with AWS_ACCESS_KEY_ID /
AWS_SECRET_ACCESS_KEY credentials.

This extends the notion of storing credentials under
`std/registry/<host>`, by first looking for a `cred_helper` file.

if the `cred_helper` is empty (or missing), we will look for username /
password files (as we already do); however, if the value is `ecr-login`,
we will then read from `std/registry/<host>/AWS_ACCESS_KEY_ID` and
`std/registry/<host>/AWS_SECRET_ACCESS_KEY` secrets, and pass those to
the ecr-login credential library. Note that it is not required to have
`docker-credential-ecr-login` installed anywhere on your PATH.

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

diff --git a/tests/registry-command/Earthfile b/tests/registry-command/Earthfile
--- a/tests/registry-command/Earthfile
+++ b/tests/registry-command/Earthfile
@@ -17,9 +17,36 @@ FROM ../..+earthly-integration-test-base \
 
 IMPORT .. AS tests
 
+RUN apk add bash
 WORKDIR /test
 
+test-dockerhub:
+    COPY lock.sh unlock.sh \
+        test-dockerhub-project.sh test-dockerhub-user.sh \
+        .
+    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
+        --secret AWS_ACCESS_KEY_ID=aws/ci-cd-access-key \
+        --secret AWS_SECRET_ACCESS_KEY=aws/ci-cd-access-secret \
+        ./lock.sh && ( \
+            ./test-dockerhub-user.sh && \
+            ./test-dockerhub-project.sh && \
+            true) || ( ./unlock.sh && echo "dockerhub test failed"; exit 1) && ./unlock.sh
+
+test-ecr:
+    COPY lock.sh unlock.sh \
+        test-ecr.sh \
+        test-ecr-project.sh test-ecr-user.sh \
+        .
+
+    ENV EARTHLY_EXEC_CMD=/test/test-ecr.sh
+    RUN --secret EARTHLY_TOKEN=fake-user-write-token \
+        --secret AWS_ACCESS_KEY_ID=aws/ci-cd-access-key \
+        --secret AWS_SECRET_ACCESS_KEY=aws/ci-cd-access-secret \
+        --mount=type=tmpfs,target=/tmp/earthly \
+        --privileged \
+        --entrypoint \
+        --mount=type=tmpfs,target=/tmp/earthly
+
 test:
-    COPY test-project.sh test-user.sh lock.sh unlock.sh .
-    RUN --no-cache --secret EARTHLY_TOKEN=fake-user-write-token \
-        ./lock.sh && ( ./test-user.sh && ./test-project.sh) || ( ./unlock.sh && echo "test failed"; exit 1) && ./unlock.sh
+    BUILD +test-dockerhub
+    BUILD +test-ecr
