Auto install bash completion file on debian
Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

diff --git a/release/apt-repo/Earthfile b/release/apt-repo/Earthfile
--- a/release/apt-repo/Earthfile
+++ b/release/apt-repo/Earthfile
@@ -7,6 +7,7 @@ deps:
 deb:
     ARG RELEASE_TAG
     ARG EARTHLY_PLATFORM
+    RUN test ! -z "$EARTHLY_PLATFORM" || (echo "EARTHLY_PLATFORM is required" && exit 1)
     ARG EARTHLY_VERSION=$(echo "$RELEASE_TAG" | cut -c 2-)
     ARG PKG_NAME=earthly_${EARTHLY_VERSION}-1_${EARTHLY_PLATFORM}
     FROM +deps
@@ -16,6 +17,9 @@ deb:
     RUN (echo "$RELEASE_TAG" | grep '^v[0-9]\+.[0-9]\+.[0-9]\+$' > /dev/null) || (echo "RELEASE_TAG must be formatted as v1.2.3; instead got \"$RELEASE_TAG\""; exit 1)
     RUN wget -q "https://github.com/earthly/earthly/releases/download/v${EARTHLY_VERSION}/earthly-linux-$EARTHLY_PLATFORM" -O $PKG_NAME/usr/bin/earthly && chmod +x $PKG_NAME/usr/bin/earthly
     COPY earthly.control $PKG_NAME/DEBIAN/control
+    COPY postinst $PKG_NAME/DEBIAN/postinst
+    COPY postrm $PKG_NAME/DEBIAN/postrm
+    RUN chmod 0555 $PKG_NAME/DEBIAN/postinst $PKG_NAME/DEBIAN/postrm
     RUN sed -i "s/__earthly_version__/$EARTHLY_VERSION/" $PKG_NAME/DEBIAN/control
     RUN dpkg -b $PKG_NAME
     SAVE ARTIFACT $PKG_NAME.deb AS LOCAL output/debs/$PKG_NAME.deb
