perform linting of CHANGELOG.md
- Ensure the CHANGELOG.md file can be correctly parsed
- Changed parser to be more strict in what is accepted:
  - all unordered items must start with `- `,
  - only 'Added', 'Changed', 'Removed', 'Fixed' H3 headers are allowed
    under version releases
  - errors now display the corresponding changelog line number
- Allow changelogparser to read from stdin

Signed-off-by: Alex Couture-Beil <alex@earthly.dev>

diff --git a/release/Earthfile b/release/Earthfile
--- a/release/Earthfile
+++ b/release/Earthfile
@@ -54,7 +54,8 @@ release-notes:
     COPY changelogparser.py /usr/bin/changelogparser
     COPY ..+changelog/CHANGELOG.md .
     ARG RELEASE_TAG
-    RUN changelogparser CHANGELOG.md $RELEASE_TAG > notes.txt
+    RUN test -n "$RELEASE_TAG" || (echo "ERROR: RELEASE_TAG is missing" && exit 1)
+    RUN changelogparser --changelog CHANGELOG.md --version "$RELEASE_TAG" > notes.txt
     SAVE ARTIFACT notes.txt
 
 release-github:
