OOM score adjustment should tolerate missing pids better

diff --git a/buildkitd/oom-adjust.sh.template b/buildkitd/oom-adjust.sh.template
--- a/buildkitd/oom-adjust.sh.template
+++ b/buildkitd/oom-adjust.sh.template
@@ -8,7 +8,12 @@ fi
 
 for PID in $(pidof buildkit-runc)
 do
-    PID_NAME=$(cat /proc/"$PID"/cmdline)
+    if [ ! -f /proc/"$PID"/cmdline ]; then
+        ! "${BUILDKIT_DEBUG}" || echo "$(date) | $PID was missing, ignoring" >> /var/log/oom_adj
+        continue
+    fi
+
+    PID_NAME=$(cat /proc/"$PID"/cmdline || echo "unknown")
     ! "${BUILDKIT_DEBUG}" || echo "$(date) | Checking $PID($PID_NAME)..." >> /var/log/oom_adj
 
     if [ "$PID_NAME" = "buildkit-runcinit" ]; then
@@ -16,14 +21,20 @@ do
         continue
     fi
 
-    #childpids=$(pgrep -P "$PID" | xargs)
     for CHILD_PID in $(pgrep -P "$PID")
     do
-        ! "${BUILDKIT_DEBUG}" || echo "$(date) |   $PID has child: $CHILD_PID($(cat /proc/"$CHILD_PID"/cmdline)) with oom_score_adj: $(cat /proc/"$CHILD_PID"/oom_score_adj)" >> /var/log/oom_adj
+        if [ ! -f /proc/"$CHILD_PID"/cmdline ]; then
+            ! "${BUILDKIT_DEBUG}" || echo "$(date) |   $CHILD_PID was missing, ignoring" >> /var/log/oom_adj
+            continue
+        fi
+
+        CHILD_PID_NAME=$(cat /proc/"$CHILD_PID"/cmdline || echo "unknown")
+        CHILD_OON_ADJ=$(cat /proc/"$CHILD_PID"/oom_score_adj || echo "unknown")
+        ! "${BUILDKIT_DEBUG}" || echo "$(date) |   $PID has child: $CHILD_PID($CHILD_PID_NAME) with oom_score_adj: $CHILD_OON_ADJ)" >> /var/log/oom_adj
     done
 
     ! "${BUILDKIT_DEBUG}" || echo "$(date) |   Adjusting pid $PID oom_score_adj to ${OOM_SCORE_ADJ}" >> /var/log/oom_adj
-    ! "${BUILDKIT_DEBUG}" || echo "${OOM_SCORE_ADJ}" > /proc/"$PID"/oom_score_adj
+    echo "${OOM_SCORE_ADJ}" > /proc/"$PID"/oom_score_adj || true # It is ok if the OOM score fails - the PID may have exited, so it no longer matters anyways.
 done
 
 ! "${BUILDKIT_DEBUG}" || echo "$(date) | --" >> /var/log/oom_adj
