Integration tests

diff --git a/examples/tests/Earthfile b/examples/tests/Earthfile
--- a/examples/tests/Earthfile
+++ b/examples/tests/Earthfile
@@ -414,3 +414,20 @@ target-first-line:
         --entrypoint \
         --mount=type=tmpfs,target=/tmp/earthly \
         -- --no-output +test
+
+if-exists:
+    COPY if-exists.earth ./Earthfile
+    RUN --privileged \
+        --entrypoint \
+        --mount=type=tmpfs,target=/tmp/earthly \
+        -- +save-exist-local
+
+    # test that the 'failed with exit code' text is printed out
+    RUN --privileged \
+        --mount=type=tmpfs,target=/tmp/earthly \
+        /usr/bin/earthly-buildkitd-wrapper.sh +save-not-exist 2>&1 | perl -pe 'BEGIN {$status=1} END {exit $status} $status=0 if /save-not-exist/;'
+
+    # test that the 'failed with exit code' text is printed out
+    RUN --privileged \
+        --mount=type=tmpfs,target=/tmp/earthly \
+        /usr/bin/earthly-buildkitd-wrapper.sh +copy-not-exist 2>&1 | perl -pe 'BEGIN {$status=1} END {exit $status} $status=0 if /copy-not-exist/;'
