Create a selfsigned https-base git server
Rather than using a public readonly GH token, we will create a
self-hosted, self-signed https-git webserver.

diff --git a/examples/tests/Earthfile b/examples/tests/Earthfile
--- a/examples/tests/Earthfile
+++ b/examples/tests/Earthfile
@@ -716,56 +716,137 @@ true-false-flag-invalid:
     DO +RUN_EARTHLY --earthfile=true-false-flag-invalid.earth --should_fail=true --target=+run-maybe --post_command="2>output3.txt"
     RUN cat output3.txt | grep 'invalid argument for flag .*--no-cache.*expected bool'
 
+# git-webserver creates a self-signed root CA, adds that CA as a trusted CA, creates a new https cert and signs it with the CA
+# then sets up an https-based git server using nginx; this repo can then be cloned by running
+# "git clone https://testuser:keepitsecret@selfsigned.example.com/repo.git"
+git-webserver:
+    RUN apk add --update --no-cache nginx openssl curl perl strace git-daemon fcgiwrap spawn-fcgi
+
+    # create a selfsigned CA
+    RUN openssl genrsa -out /root/selfsigned-ca.key 2048
+    RUN openssl req -x509 -new -nodes -key /root/selfsigned-ca.key -days 9999 \
+        -out /usr/local/share/ca-certificates/SelfSigned_Root_CA.crt -subj "/CN=test-ca"
+    RUN update-ca-certificates
+
+    RUN echo "
+[req]
+req_extensions = v3_req
+distinguished_name = req_distinguished_name
+[req_distinguished_name]
+[ v3_req ]
+basicConstraints = CA:FALSE
+keyUsage = nonRepudiation, digitalSignature, keyEncipherment
+extendedKeyUsage = clientAuth, serverAuth
+" > /root/openssl.config
+
+    # create an ssl cert
+    RUN openssl genrsa -out /root/selfsigned-example-com.key 2048
+
+    RUN openssl req -new -key /root/selfsigned-example-com.key -out /root/selfsigned-example-com.csr \
+        -subj "/CN=selfsigned.example.com" -config /root/openssl.config
+
+    RUN openssl x509 -req -in /root/selfsigned-example-com.csr -CA /etc/ssl/certs/ca-cert-SelfSigned_Root_CA.pem \
+        -CAkey /root/selfsigned-ca.key -CAcreateserial -out /root/selfsigned-example-com.pem \
+        -days 9999 -extensions v3_req -extfile /root/openssl.config
+
+    RUN mkdir -p /var/git/repos
+    RUN git init --bar /var/git/repos/repo.git
+    RUN chown -R nginx:nginx /var/git/repos
+
+    # setup basic http auth for user=testuser; password=keepitsecret; which will be used to support authenticating
+    # requests to https://testuser:keepitsecret@selfsigned.example.com
+    RUN echo "testuser:{SHA}16usTToGj2dhTan3gF5/aToe4Ro=" > /var/git/htpasswd
+
+    COPY git-webserver.nginx /root/nginx.conf
+    RUN echo "set -e
+# Docker creates /etc/hosts as readonly; we must unmount it first
+# before we can update it; this change WILL not stick around between different RUNs
+# furthermore, we must execute this script with RUN --privileged
+cp /etc/hosts /tmp/hosts
+umount /etc/hosts
+cp /tmp/hosts /etc/hosts
+if ! grep selfsigned /etc/hosts 2>/dev/null; then
+    echo -e \"127.0.0.1\tselfsigned.example.com\" >> /etc/hosts
+fi
+
+spawn-fcgi -u nginx -s /var/run/fcgi.sock /usr/bin/fcgiwrap && \
+nginx -c /root/nginx.conf
+" > /bin/start-nginx-with-git && chmod +x /bin/start-nginx-with-git
+
+    RUN --privileged start-nginx-with-git && \ # starts in background
+        mkdir -p /test/repo && \
+        cd /test/repo && \
+        git init --initial-branch=main . && \
+        echo -e "FROM alpine:3.13\nhello:\n\tRUN echo -n 98e15fb5-197c-43bf-886e-3291e65d646e | base64" > Earthfile && \
+        git add Earthfile && \
+        git config --global user.email "onlyspammersemailthis@earthly.dev" && \
+        git config --global user.name "test name" && \
+        git commit -m "An Earthfile to test against" && \
+        git remote add origin https://testuser:keepitsecret@selfsigned.example.com/repo.git && \
+        git push --set-upstream origin main && \
+        cd .. && \
+        rm -rf repo # remove this repo dir now that it has been pushed to the server
+
+
 scrub-git-clone-credentials:
-    # This token is setup with read only access to public repos
-    ARG PUBLIC_TOKEN="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"
+    FROM +git-webserver
     RUN --no-cache echo "#!/bin/sh
 set -ex
-earthly --config \$earthly_config config git \"{github.com: {auth: https, user: cinnamonthecat, password: $PUBLIC_TOKEN}}\"
-earthly --config \$earthly_config --verbose +gitclone >output.txt 2>&1
+
+# first ensure these two /etc/hosts entries are working
+ping -c 1 selfsigned.example.com
+ping -c 1 buildkitsandbox
+
+earthly --config \$earthly_config config git \"{selfsigned.example.com: {auth: https, user: testuser, password: keepitsecret, pattern: 'selfsigned.example.com/([^/]+)'}}\"
+earthly --config \$earthly_config --verbose -D +gitclone >output.txt 2>&1
 " >/tmp/test-earthly-script && chmod +x /tmp/test-earthly-script
 
-    DO +RUN_EARTHLY --earthfile=scrub-credentials.earth --exec_cmd=/tmp/test-earthly-script
+    DO +RUN_EARTHLY --pre_command=start-nginx-with-git --earthfile=scrub-credentials.earth --exec_cmd=/tmp/test-earthly-script
 
     RUN cat output.txt | grep -vw echo | grep 'gitclone done'
     RUN cat output.txt && \
-        if grep "$PUBLIC_TOKEN" output.txt >/dev/null; then \
-            echo "ERROR: password ($PUBLIC_TOKEN) was leaked" && exit 1; \
+        if grep "keepitsecret" output.txt >/dev/null; then \
+            echo "ERROR: password (keepitsecret) was leaked" && exit 1; \
         else \
             echo "OK: password was not leaked"; \
         fi
-    RUN grep 'https://cinnamonthecat:\*\*\*@github.com' output.txt >/dev/null
+    RUN grep 'https://testuser:\*\*\*@selfsigned.example.com' output.txt >/dev/null
 
 scrub-remote-credentials:
-    # This token is setup with read only access to public repos
-    ARG PUBLIC_TOKEN="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"
+    FROM +git-webserver
     RUN --no-cache echo "#!/bin/sh
 set -ex
-earthly --config \$earthly_config config git \"{github.com: {auth: https, user: cinnamonthecat, password: $PUBLIC_TOKEN}}\"
-earthly --config \$earthly_config --verbose github.com/earthly/test-remote/privileged+regular >output.txt 2>&1
+
+# first ensure these two /etc/hosts entries are working
+ping -c 1 selfsigned.example.com
+ping -c 1 buildkitsandbox
+
+earthly --config \$earthly_config config git \"{selfsigned.example.com: {auth: https, user: testuser, password: keepitsecret, pattern: 'selfsigned.example.com/([^/]+)'}}\"
+earthly --config \$earthly_config --verbose selfsigned.example.com/repo:main+hello >output.txt 2>&1
 " >/tmp/test-earthly-script && chmod +x /tmp/test-earthly-script
 
-    DO +RUN_EARTHLY --exec_cmd=/tmp/test-earthly-script
+    DO +RUN_EARTHLY --pre_command=start-nginx-with-git --exec_cmd=/tmp/test-earthly-script
 
     # make sure the password doesn't appear anywhere
     RUN cat output.txt && \
-        if grep "$PUBLIC_TOKEN" output.txt >/dev/null; then \
-            echo "ERROR: password ($PUBLIC_TOKEN) was leaked" && exit 1; \
+        if grep "keepitsecret" output.txt >/dev/null; then \
+            echo "ERROR: password (keepitsecret) was leaked" && exit 1; \
         else \
             echo "OK: password was not leaked"; \
         fi
     # make sure the scrubbed URL appears somewhere
-    RUN grep 'https://cinnamonthecat:\*\*\*@github.com' output.txt >/dev/null
+    RUN grep 'https://testuser:\*\*\*@selfsigned.example.com' output.txt >/dev/null
+    # echo -n 98e15fb5-197c-43bf-886e-3291e65d646e | base64
+    RUN grep 'OThlMTVmYjUtMTk3Yy00M2JmLTg4NmUtMzI5MWU2NWQ2NDZl' output.txt >/dev/null
+
 
 scrub-remote-credentials-on-failure:
-    # This token is setup with read only access to public repos
-    ARG PUBLIC_TOKEN="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"
     RUN --no-cache echo "#!/bin/sh
 set -ex
-earthly --config \$earthly_config config git \"{github.com: {auth: https, user: cinnamonthecat, password: $PUBLIC_TOKEN}}\"
+earthly --config \$earthly_config config git \"{github.com: {auth: https, user: cinnamonthecat, password: badpassword}}\"
 
 set +e
-earthly --config \$earthly_config --verbose github.com/cinnamonthecat/test-private+build >output.txt 2>&1
+earthly --config \$earthly_config --verbose github.com/cinnamonthecat/test-private:main+build >output.txt 2>&1
 exit_code=\$?
 if [ \$exit_code -eq 0 ]; then
     echo ERROR: earthly should have failed but didn\'t.
@@ -775,15 +856,14 @@ fi
 
     DO +RUN_EARTHLY --exec_cmd=/tmp/test-earthly-script
 
-    # PUBLIC_TOKEN should *not* have access to this private remote branch, make sure it fails
-    RUN grep 'error fetching default branch for repository' output.txt
+    RUN grep 'failed to fetch remote' output.txt
     # test the failure message correctly scrubs the credentials
     RUN grep 'https://cinnamonthecat:\*\*\*@github.com' output.txt >/dev/null
 
     # make sure the password doesn't appear anywhere
     RUN cat output.txt && \
-        if grep "$PUBLIC_TOKEN" output.txt >/dev/null; then \
-            echo "ERROR: password ($PUBLIC_TOKEN) was leaked" && exit 1; \
+        if grep "badpassword" output.txt >/dev/null; then \
+            echo "ERROR: password (badpassword) was leaked" && exit 1; \
         else \
             echo "OK: password was not leaked"; \
         fi
@@ -795,6 +875,7 @@ RUN_EARTHLY:
     ARG earthfile_dest="./Earthfile"
     ARG target=+all
     ARG extra_args
+    ARG pre_command
     ARG post_command
     ARG should_fail=false
     ARG use_tmpfs=true
@@ -807,23 +888,26 @@ RUN_EARTHLY:
         if $use_tmpfs; then
             export EARTHLY_TMP_DIR=/tmp/earthly-tmpfs
         fi
+        if [ -n \"$pre_command\" ]; then
+            eval \"$pre_command\"
+        fi
         if [ -n \"$exec_cmd\" ]; then
-          if [ \"$exec_cmd\" = \"/tmp/earthly-script\" ]; then
-            echo \"exec_cmd can not be /tmp/earthly-script\"
-            exit 1
-          fi
-          if [ \"$target\" != \"+all\" ]; then
-            echo \"target can not be used with exec_cmd\"
-            exit 1
-          fi
-          export EARTHLY_EXEC_CMD=\"$exec_cmd\"
-          echo running earthly with EARTHLY_EXEC_CMD=\$EARTHLY_EXEC_CMD
-          /bin/sh /usr/bin/earthly-entrypoint.sh
-          exit_code=\$?
+            if [ \"$exec_cmd\" = \"/tmp/earthly-script\" ]; then
+                echo \"exec_cmd can not be /tmp/earthly-script\"
+                exit 1
+            fi
+            if [ \"$target\" != \"+all\" ]; then
+                echo \"target can not be used with exec_cmd\"
+                exit 1
+            fi
+            export EARTHLY_EXEC_CMD=\"$exec_cmd\"
+            echo running earthly with EARTHLY_EXEC_CMD=\$EARTHLY_EXEC_CMD
+            /bin/sh /usr/bin/earthly-entrypoint.sh
+            exit_code=\$?
         else
-          echo running earthly with $target
-          eval \"/usr/bin/earthly-entrypoint.sh $extra_args $target $post_command\"
-          exit_code=\$?
+            echo running earthly with $target
+            eval \"/usr/bin/earthly-entrypoint.sh $extra_args $target $post_command\"
+            exit_code=\$?
         fi
         if $should_fail; then
             if [ \$exit_code -eq 0 ]; then
